name: Build

on:
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.2.0          
    
    - name: Restore NuGet packages
      run: nuget restore SimpleFrameworkApp.sln

    - name: Build
      run: msbuild SimpleFrameworkApp.sln /p:Configuration=Release

    - name: Publish to folder
      run: msbuild SimpleFrameworkApp.sln /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl='published' /p:PackageAsSingleFile=false
